version: '3'

services:
  geo_db:
    image: postgis/postgis:11-3.1
    restart: always
    environment:
      POSTGRES_DB: postgis
      POSTGRES_USER: django
      POSTGRES_PASSWORD: yolo
    ports:
      - 5432:5432
  backend_api:
    container_name: backend_api
    restart: always
    build: backend/API/
    ports:
      - 8080:8080
    depends_on:
      - geo_db
  front:
    container_name: web
    build: frontend/
    ports:
      - 3000:3000