export const SEARCH_PAGE_REQUEST_DATA = "SEARCH_PAGE_REQUEST_DATA";
export const SEARCH_PAGE_RECEIVE_DATA = "SEARCH_PAGE_RECEIVE_DATA";
export const SEARCH_PAGE_INVALIDATE_DATA = "SEARCH_PAGE_INVALIDATE_DATA";

export const LANDING_PAGE_REQUEST_DATA = "LANDING_PAGE_REQUEST_DATA";
export const LANDING_PAGE_RECEIVE_DATA = "LANDING_PAGE_RECEIVE_DATA";
export const LANDING_PAGE_INVALIDATE_DATA = "LANDING_PAGE_INVALIDATE_DATA";

/* Filter actions */
export const SEARCH_PAGE_UPDATE_FILTER_VALUE =
  "SEARCH_PAGE_UPDATE_FILTER_VALUE";

export const LOGIN = "LOGIN";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
